"""Crear tablas tecnicos, clientes, tickets

Revision ID: ee041b79f5da
Revises: 542f75ae97b5
Create Date: 2025-07-10 04:02:04.833881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee041b79f5da'
down_revision: Union[str, Sequence[str], None] = '542f75ae97b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
